// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blog_receitas_api.Models;

namespace blog_receitas_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220310040735_atualizacao-receitas")]
    partial class atualizacaoreceitas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("blog_receitas_api.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Quatidade")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("blog_receitas_api.Models.ModoDePreparo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ModoDePreparos");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Portions")
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("destaque")
                        .HasColumnType("int");

                    b.Property<byte[]>("img")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipoId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Ingrediente", b =>
                {
                    b.HasOne("blog_receitas_api.Models.Receita", "Receita")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("blog_receitas_api.Models.ModoDePreparo", b =>
                {
                    b.HasOne("blog_receitas_api.Models.Receita", "Receita")
                        .WithMany("ModoDePreparos")
                        .HasForeignKey("ReceitaId");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Receita", b =>
                {
                    b.HasOne("blog_receitas_api.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog_receitas_api.Models.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("blog_receitas_api.Models.Receita", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("ModoDePreparos");
                });
#pragma warning restore 612, 618
        }
    }
}
